name: Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: PickleChees/hello-world-docker-action@V1
        with:
          who-to-greet: '@octocat'
